# Generated by Django 4.1.2 on 2023-03-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
